import type { Metadata } from "next";
import "./globals.css";
import type React from "react";
import { Providers } from "../lib/providers";

export const metadata: Metadata = {
  title: "Assetify Desk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
